AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create basic FIS experiment for autoscaling group'

Resources:
  ExperimentTemplate:
    Type: 'AWS::FIS::ExperimentTemplate'
    Properties:
      Description: 'terminating a single instance'
      Actions:
        stopInstances:
          ActionId: 'aws:ec2:terminate-instances'
          Targets:
            Instances: oneRandomInstance
      Targets:
        oneRandomInstance:
          ResourceTags:
            'app': 'poultry'
          ResourceType: 'aws:ec2:instance'
          SelectionMode: 'COUNT(1)'
      StopConditions:
        - Source: 'none'
      Tags:
        Name: 'fisTerminateInstance'
      RoleArn: !GetAtt FISRole.Arn
  FISRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'fis.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'FISRoleEC2Actions'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:RebootInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:StartInstances'
                  - 'ec2:TerminateInstances'
                Resource: 'arn:aws:ec2:*:*:instance/*'
Outputs:
  FIS:
    Description: Template Id
    Value:
      Fn::GetAtt:
        - ExperimentTemplate
        - Id

